### ISSUE TITLE
Why do we need to add this header?

### ISSUE THREAD

**Issue by Nyholm** [php-http/cakephp-adapter#1]
https://github.com/php-http/cakephp-adapter/blob/master/src/Client.php#L50-L52

**Comment by joelwurtz** [comment]
Since it's using fopen with a http context, it's required otherwise it throws an error on the PHP Side if not present on a POST request, didnt have the time to see if there is an other way to do this (or if this is required in a POST request for HTTP 1.0 / 1.1)

But i think there may a better default value.
